# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins:
  - jekyll-gist
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            'wise {hacking}'
tagline:          'Scala, Google Cloud Platform and Terraform'
description:      'Scala, Google Cloud Platform and Terraform'
url:              http://bchazalet.github.io
baseurl:          /

author:
  name:           'Boris Chazalet'
  url:            http://bchazalet.github.io

paginate:         5

# Custom vars
