# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'lazy {hacking}'
tagline:          'embrace your lazyness'
description:      'embrace your lazyness'
url:              http://bchazalet.github.io
baseurl:          /

author:
  name:           'Boris Chazalet'
  url:            http://bchazalet.github.io

paginate:         5

# Custom vars
